version: '3.8'  
services:
  web-service:
    build:
      context: ./frontend/
      dockerfile: Dockerfile  
    ports:
      - "3000:3000"  
    env_file:
      - /frontend/.env
    networks:
      - app-network  
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    env_file:
      - /backend/.env
    ports:
      - "4000:4000"
    networks:
      - app-network
    restart: unless-stopped  

networks:  
  app-network:
    driver: bridge